### PR TITLE
improvements for 0.1.4 release

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
- [x] adds visual regression tests
- [x] gets rid of NOTE in CRAN daily checks (https://cran.r-project.org/web/checks/check_results_ggcorrplot.html)
- [x] gets rid of warning with `ggplot2 3.3.5`
- [x] bumps needed version of `ggplot2`
- [x] adopt tidyverse convention for formatting `DESCRIPTION` file
- [x] spelling check
- [x] styling (code and `NEWS.md`)
- [x] adds me as a contributor

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
I think it'd be a good idea to make a `CRAN` release soon before the `NOTE` about `lazyData` turn into a `warning`.
Also, `ggplot2` warnings would be annoying for the users.

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by IndrajeetPatil** [comment]
This been pending for over a year now, and I am guessing it's unlikely that this PR will be merged anytime soon, if ever.

**Comment by IndrajeetPatil** [comment]
Sorry, I have already deleted the fork, so there is no way to resurrect this.

**Comment by kassambara** [comment]
I downloade the code corresponding to your commit (https://github.com/kassambara/ggcorrplot/tree/51ade00c2e19d409b6519589c1f9ef6c9ef3c36f) and pushed it as a new branch (https://github.com/kassambara/ggcorrplot/tree/indrajeetPatil-improvment). I will review it and merge for submission to CRAN, thanks again

**Comment by IndrajeetPatil** [comment]
That's awesome! Didn't know there was a way to recover this. Good to know, thanks.

**Pull request closed without merging**
